export const MODULE_NAME = 'character_visual';
export const MACRO_NAME = 'current_outfit';
export const DATA_VERSION = 1;

export const DEFAULT_FIELDS = Object.freeze([
    {
        id: 'hair',
        icon: 'fa-solid fa-scissors',
        builtIn: true,
        labels: { en: 'Hair', ru: 'Причёска' },
    },
    {
        id: 'top',
        icon: 'fa-solid fa-shirt',
        builtIn: true,
        labels: { en: 'Top', ru: 'Верх' },
    },
    {
        id: 'bottom',
        icon: 'fa-solid fa-person',
        builtIn: true,
        labels: { en: 'Bottom', ru: 'Низ' },
    },
    {
        id: 'one_piece',
        icon: 'fa-solid fa-person-dress',
        builtIn: true,
        labels: { en: 'One-piece outfit', ru: 'Цельный наряд' },
    },
    {
        id: 'outerwear',
        icon: 'fa-solid fa-vest',
        builtIn: true,
        labels: { en: 'Outerwear', ru: 'Верхняя одежда' },
    },
    {
        id: 'underwear',
        icon: 'fa-solid fa-layer-group',
        builtIn: true,
        labels: { en: 'Underwear', ru: 'Нижнее бельё' },
    },
    {
        id: 'legwear',
        icon: 'fa-solid fa-socks',
        builtIn: true,
        labels: { en: 'Legwear', ru: 'Чулки и носки' },
    },
    {
        id: 'footwear',
        icon: 'fa-solid fa-shoe-prints',
        builtIn: true,
        labels: { en: 'Footwear', ru: 'Обувь' },
    },
    {
        id: 'accessories',
        icon: 'fa-solid fa-gem',
        builtIn: true,
        labels: { en: 'Accessories', ru: 'Аксессуары' },
    },
    {
        id: 'other',
        icon: 'fa-solid fa-ellipsis',
        builtIn: true,
        labels: { en: 'Other', ru: 'Прочее' },
    },
]);

export const STRINGS = Object.freeze({
    en: {
        title: 'Character Visual',
        floatingButton: 'Outfit',
        editor: 'Current outfit',
        wardrobe: 'Wardrobe',
        settings: 'Settings',
        close: 'Close',
        back: 'Back',
        noOutfit: 'No outfit selected',
        noOutfitPrompt: 'Outfit not specified.',
        unsavedOutfit: 'Unsaved outfit',
        chooseOutfit: 'Choose outfit',
        saveOutfit: 'Save outfit',
        updateOutfit: 'Update outfit',
        saveAsNew: 'Save as new',
        clearCurrent: 'Clear current',
        uploadImage: 'Upload image',
        replaceImage: 'Replace image',
        removeImage: 'Remove image',
        preview: 'Preview',
        noImage: 'No image uploaded',
        outfitDetails: 'Outfit details',
        allFolders: 'All folders',
        folder: 'Folder',
        folders: 'Folders',
        newFolder: 'New folder',
        renameFolder: 'Rename folder',
        deleteFolder: 'Delete folder',
        defaultFolder: 'My wardrobe',
        emptyWardrobe: 'No saved outfits here yet.',
        apply: 'Apply',
        edit: 'Edit',
        rename: 'Rename',
        move: 'Move',
        delete: 'Delete',
        outfitName: 'Outfit name',
        folderName: 'Folder name',
        create: 'Create',
        cancel: 'Cancel',
        save: 'Save',
        confirmDeleteOutfit: 'Delete this saved outfit? Current chat snapshots will keep their text, but may lose this image.',
        confirmDeleteFolder: 'Delete this empty folder?',
        folderNotEmpty: 'Move or delete the outfits in this folder first.',
        cannotDeleteOnlyFolder: 'The only folder cannot be deleted.',
        saved: 'Outfit saved.',
        updated: 'Outfit updated.',
        applied: 'Outfit applied to this chat.',
        cleared: 'Current outfit cleared.',
        imageSaved: 'Image uploaded.',
        storageError: 'Could not save data to browser storage.',
        uiLanguage: 'Interface language',
        promptLanguage: 'Prompt label language',
        auto: 'Auto',
        english: 'English',
        russian: 'Russian',
        showFloating: 'Show floating Outfit button',
        resetLayout: 'Reset panel position and size',
        layoutReset: 'Panel layout reset.',
        fields: 'Outfit fields',
        manageFields: 'Manage outfit fields',
        addField: 'Add field',
        resetFields: 'Restore default fields',
        fieldName: 'Field name',
        moveUp: 'Move up',
        moveDown: 'Move down',
        exportBackup: 'Export backup',
        importBackup: 'Import backup',
        backup: 'Backup',
        exportDone: 'Backup exported.',
        importDone: 'Backup imported.',
        importConfirm: 'Importing will replace this account’s current wardrobe library. Continue?',
        invalidBackup: 'This is not a valid Character Visual backup.',
        openPanel: 'Open Character Visual',
        currentChatHint: 'Changes here are saved only for the current chat until you save or update a wardrobe outfit.',
        savedOutfitHint: 'The wardrobe stores complete looks. Folder names are only for organization and never enter the prompt.',
        fieldsHint: 'Empty fields are omitted from {{current_outfit}}. Custom field names are used in both interface and prompt.',
        noChat: 'Open a chat to use Character Visual.',
        requiredName: 'Enter a name first.',
        selectFolder: 'Select a folder',
        imageTooLarge: 'The selected image is too large for browser storage.',
        importFailed: 'Could not import the backup.',
        imageFailed: 'Could not process that image.',
        search: 'Search outfits',
        noMatches: 'No outfits match this search.',
    },
    ru: {
        title: 'Визуал персонажа',
        floatingButton: 'Outfit',
        editor: 'Текущий образ',
        wardrobe: 'Гардероб',
        settings: 'Настройки',
        close: 'Закрыть',
        back: 'Назад',
        noOutfit: 'Образ не выбран',
        noOutfitPrompt: 'Образ не указан.',
        unsavedOutfit: 'Несохранённый образ',
        chooseOutfit: 'Выбрать образ',
        saveOutfit: 'Сохранить образ',
        updateOutfit: 'Обновить образ',
        saveAsNew: 'Сохранить как новый',
        clearCurrent: 'Очистить текущий',
        uploadImage: 'Загрузить изображение',
        replaceImage: 'Заменить изображение',
        removeImage: 'Удалить изображение',
        preview: 'Превью',
        noImage: 'Изображение не загружено',
        outfitDetails: 'Тело и одежда',
        allFolders: 'Все папки',
        folder: 'Папка',
        folders: 'Папки',
        newFolder: 'Новая папка',
        renameFolder: 'Переименовать папку',
        deleteFolder: 'Удалить папку',
        defaultFolder: 'Мой гардероб',
        emptyWardrobe: 'Здесь пока нет сохранённых образов.',
        apply: 'Выбрать',
        edit: 'Редактировать',
        rename: 'Переименовать',
        move: 'Переместить',
        delete: 'Удалить',
        outfitName: 'Название образа',
        folderName: 'Название папки',
        create: 'Создать',
        cancel: 'Отмена',
        save: 'Сохранить',
        confirmDeleteOutfit: 'Удалить сохранённый образ? Текст останется в текущих чатах, но его изображение может пропасть.',
        confirmDeleteFolder: 'Удалить пустую папку?',
        folderNotEmpty: 'Сначала перемести или удали образы из этой папки.',
        cannotDeleteOnlyFolder: 'Нельзя удалить единственную папку.',
        saved: 'Образ сохранён.',
        updated: 'Образ обновлён.',
        applied: 'Образ выбран для этого чата.',
        cleared: 'Текущий образ очищен.',
        imageSaved: 'Изображение загружено.',
        storageError: 'Не удалось сохранить данные в хранилище браузера.',
        uiLanguage: 'Язык интерфейса',
        promptLanguage: 'Язык названий в промте',
        auto: 'Авто',
        english: 'English',
        russian: 'Русский',
        showFloating: 'Показывать плавающую кнопку Outfit',
        resetLayout: 'Сбросить положение и размер окна',
        layoutReset: 'Положение и размер окна сброшены.',
        fields: 'Поля образа',
        manageFields: 'Настроить поля образа',
        addField: 'Добавить поле',
        resetFields: 'Вернуть стандартные поля',
        fieldName: 'Название поля',
        moveUp: 'Поднять',
        moveDown: 'Опустить',
        exportBackup: 'Экспортировать копию',
        importBackup: 'Импортировать копию',
        backup: 'Резервная копия',
        exportDone: 'Резервная копия экспортирована.',
        importDone: 'Резервная копия импортирована.',
        importConfirm: 'Импорт заменит текущую библиотеку гардероба этого аккаунта. Продолжить?',
        invalidBackup: 'Это не резервная копия Character Visual.',
        openPanel: 'Открыть Визуал персонажа',
        currentChatHint: 'Изменения сохраняются только в текущем чате, пока ты не сохранишь или не обновишь образ в гардеробе.',
        savedOutfitHint: 'Гардероб хранит цельные образы. Названия папок нужны только для порядка и никогда не попадают в промт.',
        fieldsHint: 'Пустые поля не выводятся в {{current_outfit}}. Пользовательское название используется и в интерфейсе, и в промте.',
        noChat: 'Открой чат, чтобы использовать Визуал персонажа.',
        requiredName: 'Сначала введи название.',
        selectFolder: 'Выбери папку',
        imageTooLarge: 'Изображение слишком большое для хранилища браузера.',
        importFailed: 'Не удалось импортировать резервную копию.',
        imageFailed: 'Не удалось обработать изображение.',
        search: 'Поиск образов',
        noMatches: 'По этому запросу ничего не найдено.',
    },
});

export function cloneDefaultFields() {
    return DEFAULT_FIELDS.map((field) => ({
        ...field,
        labels: { ...field.labels },
    }));
}
